### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by linwenjun** [jungleli/bookmarks-Search#1]
这一行
https://github.com/jungleli/bookmarks-Search/blob/gh-pages/script/app.js#L1
有必要吗

**Comment by linwenjun** [comment]
https://github.com/jungleli/bookmarks-Search/blob/gh-pages/script/app.js#L5
事件推荐用 on 注册

**Comment by linwenjun** [comment]
https://github.com/jungleli/bookmarks-Search/blob/gh-pages/script/app.js#L13-L27
直接用$.get就好

**Comment by jungleli** [comment]
@linwenjun 觉得这样是可以增强代码可读性的。

> 这一行
> https://github.com/jungleli/bookmarks-Search/blob/gh-pages/script/app.js#L1
> 有必要吗

**Comment by jungleli** [comment]
$.ajax -> $.get
Register input event with ".on"
